import type { CreateMeasurementsPayload } from "../schemas";

export const ExampleWeightMeasurements: CreateMeasurementsPayload = {
  measurements: [
    // December 2024
    {
      measured_at: "2024-12-29",
      value: 109.7,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2024-12-30",
      value: 109.3,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2024-12-31",
      value: 108.7,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },

    // January 2025
    {
      measured_at: "2025-01-01",
      value: 107.9,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-02",
      value: 107.8,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-03",
      value: 107.7,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-04",
      value: 107.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-05",
      value: 107.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-06",
      value: 107.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-07",
      value: 107.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-08",
      value: 107.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-09",
      value: 107.1,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-10",
      value: 106.8,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-11",
      value: 106.4,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-12",
      value: 106.9,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-13",
      value: 106.8,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-14",
      value: 106.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-15",
      value: 106.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-16",
      value: 106.6,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-17",
      value: 106.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-18",
      value: 106.9,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-19",
      value: 104.8,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-20",
      value: 104.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-21",
      value: 104.4,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-22",
      value: 104.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-23",
      value: 105.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-24",
      value: 104.8,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-25",
      value: 105.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-26",
      value: 105.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-27",
      value: 104.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-28",
      value: 104.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-29",
      value: 104.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-30",
      value: 104.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-01-31",
      value: 104.1,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },

    // February 2025
    {
      measured_at: "2025-02-01",
      value: 104.3,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-02",
      value: 105.6,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-03",
      value: 105.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-04",
      value: 103.1,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-05",
      value: 103.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-06",
      value: 102.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-07",
      value: 102.8,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-08",
      value: 102.8,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-09",
      value: 102.6,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-10",
      value: 102.1,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-11",
      value: 102.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-12",
      value: 103.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-13",
      value: 101.3,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-14",
      value: 100.8,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-15",
      value: 101.1,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-16",
      value: 100.9,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-17",
      value: 100.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-18",
      value: 100.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-19",
      value: 100.4,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-20",
      value: 101.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-21",
      value: 100.9,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-22",
      value: 101.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-23",
      value: 100.4,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-24",
      value: 100.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-25",
      value: 99.85,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-26",
      value: 99.3,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-27",
      value: 99.3,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-02-28",
      value: 99.3,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },

    // March 2025
    {
      measured_at: "2025-03-01",
      value: 99.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-02",
      value: 99.1,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-03",
      value: 100.9,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-04",
      value: 100.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-05",
      value: 100.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-06",
      value: 100.4,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-07",
      value: 101.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-08",
      value: 100.9,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-09",
      value: 101.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-10",
      value: 100.4,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-11",
      value: 100.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-12",
      value: 102.6,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-13",
      value: 102.4,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-14",
      value: 102.6,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-15",
      value: 103.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-16",
      value: 102.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-17",
      value: 101.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-18",
      value: 101.3,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-19",
      value: 100.8,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-20",
      value: 101.1,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-21",
      value: 100.9,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-22",
      value: 100.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-23",
      value: 100.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-24",
      value: 100.4,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-25",
      value: 101.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-26",
      value: 100.9,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-27",
      value: 101.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-28",
      value: 100.4,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-29",
      value: 100.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-30",
      value: 99.85,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-03-31",
      value: 99.3,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },

    // April 2025
    {
      measured_at: "2025-04-01",
      value: 99.3,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-02",
      value: 94.8,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-03",
      value: 94.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-04",
      value: 93.75,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-05",
      value: 93.65,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-06",
      value: 95.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-07",
      value: 94.85,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-08",
      value: 95.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-09",
      value: 94.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-10",
      value: 94.35,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-11",
      value: 94.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-12",
      value: 94.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-13",
      value: 94.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-14",
      value: 93.55,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-15",
      value: 94.2,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-16",
      value: 95.4,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-17",
      value: 95.4,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-18",
      value: 93.75,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-19",
      value: 93.55,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-20",
      value: 93.15,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-21",
      value: 92.65,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-22",
      value: 92.6,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-23",
      value: 92.55,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-24",
      value: 93.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-25",
      value: 93.35,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-26",
      value: 93.8,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-27",
      value: 93.0,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-28",
      value: 92.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-29",
      value: 92.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
    {
      measured_at: "2025-04-30",
      value: 92.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },

    // May 2025
    {
      measured_at: "2025-05-01",
      value: 92.5,
      measurement_type_id: "weight",
      unit: "metric",
      notes: null,
    },
  ],
};
